// "npm run devStart" to run server

GET http://localhost:3000/users/ HTTP/1.1

###
POST http://localhost:3000/users 
Content-Type: application/json

{

  "email": "user@example.com",
  "username": "exampleuser",
  "password": "password123",
  "role": "user",
  "planid": 1


}

###

POST http://localhost:3000/users/login 
Content-Type: application/json

{

    "username": "Kyle", 
    "password": "password"

}
